kind: Pod
apiVersion: v1
metadata:
  name: pa-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: pa-pvc
  containers:
    - name: task-pv-container
      image: alpine:3.2
      command:
        - /bin/sh
        - "-c"
        - "sleep 60m"
      volumeMounts:
        - mountPath: "/data"
          name: task-pv-storage
