kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pa-pvc
  namespace: mario
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: pa-storageclass
