kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basic-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: pa-storageclass
